<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Make Appointment</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>fcef294c-a927-4ef3-b887-76af34a06f7b</testSuiteGuid>
   <testCaseLink>
      <guid>3bdea095-ef06-4d0d-ae53-d5b29225fd3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Make Appointment/CHS-5 Verify Add Appointment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a833b02b-7f17-47fd-84f7-893494c7de22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8d44f30-ecd5-4079-8e87-12b68491076e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb49b50e-9439-413e-b84b-c08f1bb4403e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ea1ac03-185e-4389-b678-3dcb7de1527d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Make Appointment/CHS-7 Verify Go to Make Appointment section after create a new one</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af80fff0-7117-4aeb-924e-d5fdf9bd2811</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>671b0630-e1c5-47ab-b7b8-dbcf1bd771b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Make Appointment/CHS-6 Without Input Optional Form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>826d583f-7a3e-4349-b6b5-fcd560e56a6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23f0384c-092f-4259-a91a-a5bf67600577</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd48f192-740f-4df9-8454-0acbaeead46a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Make Appointment/CHS-8 Not input Visit Date</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a833b02b-7f17-47fd-84f7-893494c7de22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8d44f30-ecd5-4079-8e87-12b68491076e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb49b50e-9439-413e-b84b-c08f1bb4403e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
